// Manifold — visualizes physical USB and Thunderbolt connections live.
// Copyright (C) 2026 Brandon Villar
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//
// ─────────────────────────────────────────────────────────────────────
// BatteryAlertConfig.swift
//
// Phase 19 — value type backing the user-managed list of low-battery
// and charged-battery threshold alerts shown in `MenuBarPane`. Stored
// as a JSON-encoded array under `SettingsKeys.batteryAlertConfigs`
// (see `BatteryAlertPreferences.swift` for the encode/decode shape).
//
// Per SPEC §21.6: `Identifiable` so SwiftUI lists can diff rows
// stably across edits, `Codable` for JSON persistence, `Hashable` so
// `BatteryAlertEngine` can track fired ids in a `Set<UUID>`.
//
// `id` is generated by the caller (`BatteryAlertPreferences.add(_:_:)`
// or the seed) and never mutated thereafter — fixing the id keeps the
// engine's `firedLowAlertIDs` / `firedChargedAlertIDs` bookkeeping
// stable across the JSON round-trip that happens whenever the
// MenuBarPane saves an edit.

import Foundation

/// One configurable battery threshold alert. Two flavors share this
/// shape via `kind`: a low-battery alert (fires on a descending
/// crossing) or a charged alert (fires on an ascending crossing while
/// charging). The fixed plug / unplug rows live as scalar UserDefaults
/// keys (`pluggedInAlertEnabled`, etc.) and are NOT instances of this
/// type — see `BatteryAlertPreferences` for the full shape.
struct BatteryAlertConfig: Identifiable, Codable, Hashable, Sendable {

    /// Two-flavor split. The percent range that's valid in the
    /// MenuBarPane stepper differs by kind (1–50 for `.low`,
    /// 50–100 for `.charged`); the engine's edge-trigger logic
    /// also branches on this.
    enum Kind: String, Codable, Hashable, CaseIterable, Sendable {
        case low
        case charged
    }

    /// Stable identity. Generated by the seed or by `add(_:_:)` on
    /// `BatteryAlertPreferences`; survives the JSON round-trip so the
    /// engine's `firedLowAlertIDs` / `firedChargedAlertIDs` sets stay
    /// keyed to the same row across edits.
    let id: UUID

    /// Low or charged. Determines edge direction + valid percent
    /// range + which seed table this row came from.
    var kind: Kind

    /// Threshold percent. Bounds enforced by the MenuBarPane
    /// `Stepper` UI (1...50 for `.low`, 50...100 for `.charged`); the
    /// engine treats any out-of-band value defensively (re-arm
    /// hysteresis still applies).
    var percent: Int

    /// Master enable for this row. UI shows the row but the engine
    /// skips it when false. The user-flow lets a power user keep a
    /// threshold configured-but-silent without deleting + re-adding it.
    var enabled: Bool

    /// Per-row sound flag. AND-composed with the master
    /// `BatteryAlertPreferences.batteryAlertsSoundEnabled` toggle
    /// before any `BatteryAlertSound.play*()` call (per SPEC §21.5).
    var playsSound: Bool

    init(
        id: UUID = UUID(),
        kind: Kind,
        percent: Int,
        enabled: Bool = true,
        playsSound: Bool = false
    ) {
        self.id = id
        self.kind = kind
        self.percent = percent
        self.enabled = enabled
        self.playsSound = playsSound
    }
}

// MARK: - Constants

/// Numeric bounds that the MenuBarPane stepper UI enforces. Lifted to
/// named constants so the inline editor + tests + any future intent
/// donor agree on the bounds without re-typing the literals.
enum BatteryAlertConfigBounds {
    /// Lowest percent the `.low` stepper allows. 1 instead of 0
    /// because "low alert at 0%" is meaningless — the device is
    /// already off by then.
    static let lowMinPercent: Int = 1

    /// Highest percent the `.low` stepper allows. 50 splits the
    /// percent range cleanly with `.charged`'s lower bound.
    static let lowMaxPercent: Int = 50

    /// Lowest percent the `.charged` stepper allows. Mirror of
    /// `lowMaxPercent`.
    static let chargedMinPercent: Int = 50

    /// Highest percent the `.charged` stepper allows. 100 = "fully
    /// charged" — useful for users who want a notification when the
    /// battery management system finishes a top-off charge.
    static let chargedMaxPercent: Int = 100
}
